# To let the CI execute the maven wrapper, use this command and push the change:
#    git update-index --chmod=+x mvnw

language: java
jdk:
  - openjdk8

env:
  global:
  - secure: "hy8rRoPkI+sEVdkkYHuBECjT153RLSv/ELbjF9CmwuP2TAxRnRjVTn/vlAnauWQ5gOnw6prcxYzKaNNKItnNCy7rQnwfOO/xFDgq7I8m1CB9IDw1qsndRQ9kA0aQcBgCsq+b5zebs7c3SA21GmTm+QdZ1uxc5fZ2LIKEyZ1W7GSf6HulOlaDrLxpnZzzP8Uo7gh7VGXuGomDhd30EUKSPwgeBNtRwqdW5o1o1uxx9a5W4MGiCHgd1p7qjUfQslRZFTdEaBnAh3fbk5rAfjqoGZ6y82Sf4mmpPdrh+dNmAEs4dc5Ag/pSyZVX3G75INopiIUUe4LbzxxLvNlKvF0q4u3U+uWjY3vfdR1qxxJHQEqcsp87ltafI10uYEP8Tc/C5s2zpaBf/hzlDkHSiuQpTxlfoEf0cKOsgxZUggp9KEWtiKwnJy2i/W/9yReAO6Uun/Ogc36Agc+a6m/yt1vzYGDwsw5KhUYe/jb2xXOVe/p5ZQZeMXb5eeLM1Ag9o/1F13wHN7GUxry0wyfkr0ut28HMcgII2YLVo8+NqisTxV8xQcKTMvO++0J9qlPSFBM2LFztCXDT3kfr4bWzH353tBz3iUh9GeKl4YGEPKwHzt2fcrmmJBI2M6oKXDaoDvuJDc0IzoCuZQVekJgUZczskNAgOHGyDfMdE5NwuAPwAJc="
  - secure: "ZVN5T24pp3vP7/BupKGCvgBvD514no54GfDrcpY0G+emRxdJTbIied6NChcXbo3nCgNClYf9oxeKQhPdySJeuqd6iNPBWlMmZ7PncXe2Otg8/5x06VtUkICccu2dHdV/9+W6qMA5Y606WV+kmuGvM40O9LEYwtckB2ufbnQpGBQ2ZExuiBjh15ppkIaU8Xl32msaxqp8DskiTa9kt9aR2SkmgSJikGcJACKniviicEfohsDbwxuGN8fAfJciUAGOhXLNcvBrvRRujHUctH+DV2tysYbwRclaimmXIeRy1AWq84v/q6ztDxAd3d+K9vd4q/vHLFcpbKYfB0Le8+G/Rley0/iv/mOOaCIPRC5xPOuXEQiiWzAGFQQ0OZYK143vqMOpxECJdALyC7YAzSG2X+9X2mjqtVIEJZD5WV7HeGtLPvNVpGUvVlctTVzeVfUCShMDHUTGoWodmeXt5MQDG9gWoECbU1Ds4nWmIpUp4bwdGFLdECkZd6M4OidxJP8KWcbP6OjThDaud9/Xh4lhJQsxE0uP25eqE04NpAPGeupGO9U5WH+ElduT6u7wjBT35zDOFpk/LUAvfa29pzejN+NEDeoVK1K45KnlBy4iLbxvC1wrbKRUZZw0dfGsYpGx5zDVPp9h082cTrCjIR+NrBXNUX8btKEqDas+LkqAwAI="

before_install:
- openssl aes-256-cbc -K $encrypted_46a968247833_key -iv $encrypted_46a968247833_iv -in keystore.jks.enc -out keystore.jks -d

script:
  - ./mvnw clean install

after_success:
- ./mvnw test jacoco:report coveralls:report

deploy:
- provider: releases
  api_key:
    secure: "1Rb1etBW4/vr587XnqQcx4OtGVFUl2dlszFKhutS4zAt+Fl3TXf6G6ehj5CxT95zo0xuDTiKONhg53AgOB5La+rZ04/QUpV+MiZbGBggZw9fIJIMR/sJcKemmFbKZrTCCWdDuD+34bbbkgwA1f7N3vBfcYQPWRbM+h1eLkuVTovDCaiczTVCx1kbIg1dngZTkiGRizf7PREjkivDIzGq75IQI0V2siV2HPjQUe1z3HVGZfgxWqaEDEQqHBVVhrO5Jr13sZEtn6/Hy/wfGTALevnYkmcs6/l5XUgANdaOAuIyhiqjtvogXw/GFdiyjY3kWt9Wxjk6D7vMnQUjoEz68X6wVMbMBEs83AZVEVQt9CB08Gtu3MPcTOPf4PPjuhJDvacJEszmbPCIpb8q/O6MtLdxJcbNYlHKJiDB7DGnQ93EEDYBV7ccEmzljlnKPAaWr/CLwUOk9JNJopfMZCzQdW2sQmx7+Tsl1eo7cvjRXyjWcFfmjwOzAGW0BgXBqVwmITVZRObamwCmohbRs6bhUXIcOSmxHYlQJryg1KeQ45lA3jghfWtFeIxSMfvG8ZbRg2tmhpwmtK3Opay48KDpRVvnORzMlZj5RHYlZI8PYmY8tTXoYAqQsfwjaRU+C81TwAlNyxRSq0vNwzHJc5rmmwExnlXzN37fkZH/tfN/3XM="
  file_glob: true
  file:
  - "target/uber-apk-signer-*.jar"
  - "target/checksum*"
  skip_cleanup: true
  on:
    branch: master
    tags: true

cache:
  directories:
  - $HOME/.m2

notifications:
  slack:
    secure: "i6MYvtBqn95n1omWyX+0WR/GzH1b29OWdN3SohE0j4B65qhTbGT9+kfPxCuzTE3LRjd/Bxm0Xce0EQpm+kE61mrDMMJjmrUS/cwnaqWuhNq0odfllnmWiNKdpe8HXRypIruIFL/ux1bkKAAisS6QRjJ4+eHjKZ4HixcKog6FIpyCWVEPjHF3EuTwV7CofPaobvCodtx8FQohtGqIev3PoB5dFl3Fe1QOM4NUdyqI1jXndsHiH0+Q8r1rAJgbmOxPrp+ioAlppIRrrpf97mzhETcEA8xXnrk2Lwl9MlrPRtxkSJlThVzdxoAJnPPwDLAmKBR4ACfn+BHUPreMHYzlTFcHXrnNPs0d6RLY6Ln3TU/e7LD0C63skqnlRw6KTuYmpJOu5781xW+jSQ42EdqazMYWIdGLe37RcPcv+EzyWjrp9wtMDxBl0IQKlpOcSScTQANJCsqUOe237Mr2OT+1FfBHRyEWE8XOsXhkQeUQoT6/iXz/IYYkstSwmVLC7W3bn3GWjqwIMjL3bWyfhCvtFmplPUM7nPlPriP1+hP5labAuDRcM20lQLjIurz1ZlCqhEflKtte8A3z97JBgQ8TWA6kPTtGKJ5H8SzyUEmqfJo7UDyfcsQEPOhio9Ah1/ETcsC+bKYwkgNoEDPboytOdId9Q4sC6dSm37bMYqXteXU="
  email: false

